### ISSUE TITLE
Sadly not working - Uncaught SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by platinumshore** [luwes/lite-vimeo-embed#11]
with demo scripts you get the following console error..

Uncaught SyntaxError: import declarations may only appear at top level of a module

**Comment by platinumshore** [comment]
Sadly also just found out not working on chrome and/or filefox - same console error "Uncaught SyntaxError: import declarations may only appear at top level of a module"

![SNAG-0194](https://user-images.githubusercontent.com/34646964/129328991-141d8d06-1504-496d-a20c-d2f924156ec4.jpg)

**Comment by p4u1d34n** [comment]
I just added  type="module" to the script 

<script type="module" src='/vimeo.js' defer></script>

that worked for me on this
