### ISSUE TITLE
Background Image is wrong

### ISSUE THREAD

**Issue by gitmathub** [luwes/lite-vimeo-embed#13]
The player used to show a preview image but now it's a "rainbow like" picture

no matter what background image I'm configuring. When the script is loaded it's replaced by:
https://i.vimeocdn.com/video/810965406.webp?mw=1600&mh=900&q=70

This is what it looks like finally:
<img width="870" alt="Screenshot 2021-11-15 at 09 06 20" src="https://user-images.githubusercontent.com/4644058/141744678-40154616-ceb0-4de9-8db5-06979c4c28a3.png">

**Comment by alexander-ronin** [comment]
> The player used to show a preview image but now it's a "rainbow like" picture
> 
> no matter what background image I'm configuring. When the script is loaded it's replaced by: https://i.vimeocdn.com/video/810965406.webp?mw=1600&mh=900&q=70
> 
> This is what it looks like finally: <img alt="Screenshot 2021-11-15 at 09 06 20" width="870" src="https://user-images.githubusercontent.com/4644058/141744678-40154616-ceb0-4de9-8db5-06979c4c28a3.png">

The same trouble. Did you found solution?

**Comment by dtirer** [comment]
I'm also experiencing this issue

**Comment by AdamBauerle** [comment]
This appears to be still ongoing. Is there still ongoing support for this or has it been abandoned? Seems to be very promising.

**Comment by hannahbeasley** [comment]
I ended up writing a solution that originally came from the @slightlyoff method to pull in thumbnails correctly. This is the pull request with the commits: https://github.com/luwes/lite-vimeo-embed/pull/14

Working great for me now!

**Comment by marcos-devarts** [comment]
This works to me:
````css
lite-vimeo {
  background-image: url('[path_to_your_image]') !important;
}
````

**Comment by csi-lk** [comment]
Same issue here and the css background image workaround doesn't seem to work
