### ISSUE TITLE
get thumbnails from vimeo is broken

### ISSUE THREAD

**Issue by fgeierst** [luwes/lite-vimeo-embed#7]
The preview image shows vertical colored bars for all videos. I think the vimeo api that returns these images may have changed?
![Anmerkung 2020-04-27 110054](https://user-images.githubusercontent.com/22551442/80354012-77769500-8876-11ea-90df-7dbfd6f309a4.jpg)

**Comment by lanaluna** [comment]
I have the same issue. And we noticed, that some people see the normal preview image and others see the stripes.
Here the difference in code:
ok:
`background-image: url(https://lite-vimeo-embed.now.sh/thumb/67577021.webp?mw=700&mh=394&q=85);`

broken:
`background-image: url(https://lite-vimeo-embed.now.sh/thumb/67577021.webp?mw=750&mh=421.875&q=85);`

If I (I see normal preview) change the screen scale (80%), I start to see stripes too.

**Comment by pcfreak30** [comment]
So you are aware, you have to get the thumbnail URLs from their API. Example `https://vimeo.com/api/v2/video/67577021.json`. 

They are not following YouTube's example.
